components:
  headers:
    LocationHeader:
      description: URI of the newly created resource
      schema:
        type: string
        format: uri
  schemas:
    book:
      properties:
        author:
          items:
            properties:
              familyName:
                type: string
              givenName:
                type: string
            type: object
          type: array
        edition:
          format: int32
          type: integer
        isbn:
          items:
            type: string
          type: array
        price:
          format: int32
          type: integer
        published:
          type: boolean
      required:
        - edition
        - isbn
        - price
        - published
      type: object
    book-edition:
      properties:
        displayName:
          type: string
      required:
        - displayName
      type: object
    publisher:
      properties:
        name:
          type: string
        description:
          type: string
      type: object
info:
  contact:
    email: email@email.com
    name: API support
  description: An API for bookstore.example.com
  title: bookstore.example.com
  version: v1
openapi: 3.1.0
paths:
  /publishers:
    get:
      description: List method for publisher
      operationId: listPublishers
      parameters:
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: pageToken
          schema:
            type: string
        - in: query
          name: skip
          schema:
            type: integer
        - in: query
          name: filter
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  nextPageToken:
                    type: string
                  results:
                    items:
                      $ref: '#/components/schemas/publisher'
                    type: array
                type: object
          description: Successful response
    post:
      description: Create method for publisher
      operationId: createPublisher
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/publisher'
        required: true
      responses:
        '201':
          headers:
            Location:
              $ref: '#/components/headers/LocationHeader'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publisher'
          description: Successful response
  /publishers/{publisher_id}:
    delete:
      description: Delete method for publisher
      operationId: deletePublisher
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: query
          name: cascade
          schema:
            type: boolean
      responses:
        '204':
          content:
            application/json:
              schema: { }
          description: Successful response
    get:
      description: Get method for publisher
      operationId: getPublisher
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publisher'
          description: Successful response
    patch:
      description: Update method for publisher
      operationId: updatePublisher
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: query
          name: updateMask
          required: true
          description: >
            Comma-separated list of field names to update.
            Only the fields listed here will be modified.
          schema:
            type: array
            items:
              type: string
              enum:
                - name
                - description
          style: form
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/publisher'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publisher'
          description: Successful response
    put:
      description: Apply method for publisher
      operationId: applyPublisher
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/publisher'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/publisher'
          description: Successful replace
        '201':
          headers:
            Location:
              $ref: '#/components/headers/LocationHeader'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful creation
  /publishers/{publisher_id}/books:
    get:
      description: List method for book
      operationId: listBooks
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: pageToken
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  nextPageToken:
                    type: string
                  results:
                    items:
                      $ref: '#/components/schemas/book'
                    type: array
                  unreachable:
                    items:
                      type: string
                    type: array
                type: object
          description: Successful response
    post:
      description: Create method for book
      operationId: createBook
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book'
        required: true
      responses:
        '201':
          headers:
            Location:
              $ref: '#/components/headers/LocationHeader'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful response
  /publishers/{publisher_id}/books/{book_id}:
    delete:
      description: Delete method for book
      operationId: deleteBook
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: path
          name: book_id
          required: true
          schema:
            type: string
        - in: query
          name: cascade
          schema:
            type: boolean
      responses:
        '204':
          content:
            application/json:
              schema: { }
          description: Successful response
    get:
      description: Get method for book
      operationId: getBook
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: path
          name: book_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful response
    patch:
      description: Update method for book
      operationId: updateBook
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: path
          name: book_id
          required: true
          schema:
            type: string
        - in: query
          name: updateMask
          required: true
          description: >
            Comma-separated list of field names to update.
            Only the fields listed here will be modified.
          schema:
            type: array
            items:
              type: string
              enum:
                - author.familyName
                - author.givenName
                - edition
                - isbn
                - price
                - published
          style: form
      requestBody:
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/book'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful response
    put:
      description: Apply method for book
      operationId: applyBook
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: path
          name: book_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful replace
        '201':
          headers:
            Location:
              $ref: '#/components/headers/LocationHeader'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
          description: Successful creation
  /publishers/{publisher_id}/books/{book_id}/editions:
    get:
      description: List method for book-edition
      operationId: listBookEditions
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: path
          name: book_id
          required: true
          schema:
            type: string
        - in: query
          name: pageSize
          schema:
            type: integer
        - in: query
          name: pageToken
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  nextPageToken:
                    type: string
                  results:
                    items:
                      $ref: '#/components/schemas/book-edition'
                    type: array
                type: object
          description: Successful response
    post:
      description: Create method for book-edition
      operationId: createBookEdition
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: path
          name: book_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book-edition'
        required: true
      responses:
        '201':
          headers:
            Location:
              $ref: '#/components/headers/LocationHeader'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book-edition'
          description: Successful response
  /publishers/{publisher_id}/books/{book_id}/editions/{book_edition_id}:
    delete:
      description: Delete method for book-edition
      operationId: deleteBookEdition
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: path
          name: book_id
          required: true
          schema:
            type: string
        - in: path
          name: book_edition_id
          required: true
          schema:
            type: string
      responses:
        '204':
          content:
            application/json:
              schema: { }
          description: Successful response
    get:
      description: Get method for book-edition
      operationId: getBookEdition
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: path
          name: book_id
          required: true
          schema:
            type: string
        - in: path
          name: book_edition_id
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book-edition'
          description: Successful response
  /publishers/{publisher_id}/books/{book_id}:archive:
    post:
      description: Custom method archive for book
      operationId: archiveBook
      parameters:
        - in: path
          name: publisher_id
          required: true
          schema:
            type: string
        - in: path
          name: book_id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: https://aep.dev/json-schema/type/operation.json
          description: Long-running operation response
servers:
  - url: http://localhost:8081
