---
openapi: 3.0.3
info:
  title: Library
  version: 1.0.0
components:
  schemas:
    VndError:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: |
            A human-readable message related to the current error which may be displayed to the user of the API.
          example: "Validation failed"
        logref:
          type: string
          description: |
            A numeric, alphabetic, or alphanumeric identifier to refer to the specific error on the server side for logging purposes (e.g., a request ID or trace ID).
          example: "42"
        path:
          type: string
          description: |
            A JSON Pointer (RFC 6901) to a field in the related resource that this error is relevant for.
          example: "/username"
        _links:
          type: object
          description: Hypermedia links related to the error.
          properties:
            about:
              $ref: '#/components/schemas/Link'
            describes:
              $ref: '#/components/schemas/Link'
            help:
              $ref: '#/components/schemas/Link'
        _embedded:
          type: object
          description: |
            Embedded error resources for representing multiple or nested errors.
          properties:
            errors:
              type: array
              items:
                $ref: '#/components/schemas/VndError'
        total:
          type: integer
          description: |
            Total count of errors when multiple errors are present.
          example: 2
    Link:
      type: object
      required:
        - href
      properties:
        href:
          type: string
          format: uri
          description: A URI or URI Template pointing to the linked resource.
          example: "https://api.example.com/users/123"
        templated:
          type: boolean
          description: Indicates whether the href is a URI Template (RFC 6570).
          example: false